// Il Catalogo centralizzato delle canzoni con gli autori
const catalogoCanzoni = [
    { titolo: "4 Marzo 43", autore: "Lucio Dalla - Sanremo 1971" },

    { titolo: "A braccia aperte", autore: "Emanuele Fossi" },
    { titolo: "A Natale puoi", autore: "Francesco Vitaloni 2005" },
    { titolo: "Abbà", autore: "De Luca, Aguila" },
    { titolo: "Abbracciami Dio dell'eternità", autore: "Rinnovamento nello Spirito Santo - Savio De Filippis, Francesco Frigiola" },
    { titolo: "Abbracciami Gesù Figliol Prodigo", autore: "Figli del Divino Amore" },
    { titolo: "Acclamate al Signore", autore: "Don Marco Frisina" },
    { titolo: "Acqua siamo noi", autore: "Giosy Cento" },
    { titolo: "Adeste fideles", autore: "Trascr. J. F. Wade" },
    { titolo: "Adoro Te Koinonia", autore: "(Koinonia) L. Arzenton" },
    { titolo: "Adoro Te", autore: "Rinnovamento nello Spirito" },
    { titolo: "Agnello di Dio Renato Giorgis", autore: "Renato Giorgis" },
    { titolo: "Agnello di Dio RnS", autore: "RnS Dino De Dominicis" },
    { titolo: "Agnello di Dio Serapiglia", autore: "GianLuigi Serapiglia" },
    { titolo: "Agnello di Dio Voce del mio canto", autore: "Gen Rosso" },
    { titolo: "Al Tuo Santo altar", autore: "E. Renoglio, Haies les Roses 1963" },
    { titolo: "Alla dolce presenza Tua, Signor", autore: "Rinnovamento nello Spirito Santo - Suella Behrns" },
    { titolo: "Alla fredda Tua capanna", autore: "S. Zimarino" },
    { titolo: "Alla Tua mensa", autore: "RnS" },
    { titolo: "Alla tua presenza", autore: "Fabio Tiddia" },
    { titolo: "Alleluia lode cosmica", autore: "Stefano Puri 2004" },
    { titolo: "Alleluja (Chiama ed io)", autore: "Luca Diliberto (T.) e Giuliana Monti (T.) 2013" },
    { titolo: "Alleluja (Dall'amore di Dio)", autore: "Fabio Baggio, Francesco Buttazzo 2014" },
    { titolo: "Alleluja (Lodate il Signore)", autore: "Don Marco Frisina" },
    { titolo: "Alleluja a colui che risuscitò", autore: "Donald Fishel (RnS)" },
    { titolo: "Alleluja al Redentore", autore: "RnS" },
    { titolo: "Alleluja chi ascolta", autore: "Francesco Buttazzo" },
    { titolo: "Alleluja è risorto il Signor", autore: "Francesco Buttazzo" },
    { titolo: "Alleluja Irlandese", autore: "F. O'Carroll" },
    { titolo: "Alleluja Kenosis", autore: "Kenosis" },
    { titolo: "Alleluja la nostra festa", autore: "Varnavà" },
    { titolo: "Alleluja lode cosmica", autore: "Stefano Puri 2004" },
    { titolo: "Alleluja San Francesco", autore: "??" },
    { titolo: "Alleluja Serapiglia", autore: "GianLuigi Serapiglia" },
    { titolo: "Alleluja Voce del mio canto", autore: "Gen Rosso" },
    { titolo: "Alzati e risplendi", autore: "A. Gocam" },
    { titolo: "Alzo gliocchi al cielo", autore: "Stefano Lo Bue 2018" },
    { titolo: "Amare è donare tutto", autore: "Don Marco Frisina" },
    { titolo: "Amatevi fratelli", autore: "D. Marchetta" },
    { titolo: "Andate per le strade", autore: "Roncari" },
    { titolo: "Andiamo Fratelli - Vieni Fratello", autore: "A. Lagorio" },
    { titolo: "Andrò a vederla un dì", autore: " Padre Pierre Janin, Francesco Molfetta 1853" },
    { titolo: "Anima di Cristo", autore: "RnS" },
    { titolo: "Annunceremo che Tu", autore: "Paolo Auricchio" },
    { titolo: "Antica eterna danza", autore: "Gen Verde, Rosso" },
    { titolo: "Arricudjitivi a casa", autore: "Canto Scout E/G" },
    { titolo: "Astro del ciel", autore: "Joseph Mohr (T.) Franz Xaver Gruber (M.) 1816-18 - don Angelo Meli 1937" },
    { titolo: "Attorno alla rupe", autore: "Canto Scout L/C" },
    { titolo: "Ave mamma tutta bella sei", autore: "Gioventù Ardente Mariana (G.A.M.)" },
    { titolo: "Ave Mamma", autore: "Gioventù Ardente Mariana" },
    { titolo: "Ave Maria (Voce del mio canto)", autore: "Gen Rosso" },
    { titolo: "Ave Maria Caccini", autore: "Giulio Caccini - Vavilov 1972" },
    { titolo: "AVE Maria di Lourdes", autore: "Don Jean Gaignet (T.), Louis Lambillotte (M.) 1873" },
    { titolo: "AVE Maria Gen verde", autore: "Gen Verde" },
    { titolo: "Ave Maria Schubert Latino", autore: "Franz Schubert (1797-1828)" },
    { titolo: "Ave Maria Verbum panis", autore: "M. Balduzzi, C.Casucci" },

    { titolo: "Batte, batte", autore: "Gen Verde (T.) Valerio Ciprì, (M.) Jocelyn K. Belamide" },
    { titolo: "Beati coloro", autore: "Gen Rosso / Gen Verde 1972" },
    { titolo: "Beati quelli che ascoltano", autore: "(M.) Ernesto Ferretti, (T.) Antonio Bagni" },
    { titolo: "Beati voi", autore: "Francesco Buttazzo" },
    { titolo: "Beatitudine", autore: "RnS Gaetano Castiglia 1984" },
    { titolo: "Benedetta sei Tu, Maria", autore: "Kiko Arguello" },
    { titolo: "Benedetto il Nome del Signor", autore: "Rinnovamento nello Spirito Santo, Don Moen nel 1986" },
    { titolo: "Benedetto sei Tu o Dio", autore: "Mauro Gioia" },
    { titolo: "Benedetto Signore (Cerco solo Te)", autore: "Rinnovamento nello Spirito Santo - Marco Cosimo Pecoraro" },
    { titolo: "Benedetto Tu Signore", autore: "Daniele Ricci" },
    { titolo: "Benedici, o Signore", autore: "Gen Rosso" },
    { titolo: "Buon Natale, in allegria", autore: "Coro dell'Antoniano" },

    { titolo: "Cammineremo nella libertà", autore: "Don Giosy Cento" },
    { titolo: "Camminerò camminerò", autore: "A. Marani" },
    { titolo: "Camminiamo incontro al Signore", autore: "A.M.Galliano, D.Semprini" },
    { titolo: "Camminiamo sulla strada", autore: "Anonimo" },
    { titolo: "Canterò per Te", autore: "Pino Fanelli" },
    { titolo: "Cantiamo Te", autore: "Marco Gragnani" },
    { titolo: "Canto a te Maria", autore: "Gen Verde" },
    { titolo: "Canto dell'addio", autore: "Canto Scout" },
    { titolo: "Canto dell'amicizia", autore: "Canto Scout" },
    { titolo: "Canto della Promessa L/C E/G", autore: "Canto Scout L/C - E/G" },
    { titolo: "Canto delle squadriglie", autore: "Canto scout E/G" },
    { titolo: "Canzone di San Damiano", autore: "Riz Ortolani - Benjamin" },
    { titolo: "Cerco la Tua Voce", autore: "Gen Rosso" },
    { titolo: "Chi ci separerà", autore: "Don Marco Frisina" },
    { titolo: "Chiamati per nome", autore: "Gen Verde" },
    { titolo: "Chiara è la tua sorgente", autore: "Pierangelo Sequeri" },
    { titolo: "Chiesa di Dio", autore: "E. Costa, C. Villeneuve" },
    { titolo: "Cieli e terra nuova", autore: "Mario Piatti & G. F. Agamennone 1969" },
    { titolo: "Come è bello, Signor", autore: "L. Mazza 1978" },
    { titolo: "Come fuoco vivo", autore: "Gen Verde e Rosso" },
    { titolo: "Come il pellicano", autore: "Gen Verde" },
    { titolo: "Come l'aurora verrai", autore: "Gen Verde" },
    { titolo: "Come Maria", autore: "Gen Rosso" },
    { titolo: "Come Tu mi vuoi", autore: "D. Branca (RnS)" },
    { titolo: "Come un Fiume", autore: "Gen Rosso" },
    { titolo: "Come un prodigio", autore: "Debora Vezzani" },
    { titolo: "Come un rabdomante", autore: "Fra' Giuseppe Di Fatta" },
    { titolo: "Con gioia veniamo a te", autore: "P. Ferrante  F.G. Pesare (RnS)" },
    { titolo: "Con Te, camminerò", autore: "Gen Verde" },
    { titolo: "Cosa offrirti", autore: "Daniele Branca e Lucia Ciancio (RnS) 2005" },
    { titolo: "Credo in Te, o Padre", autore: "Anonimo" },
    { titolo: "Credo in Te, Signore", autore: "Don Marco Frisina" },
    { titolo: "Cristo è risorto veramente", autore: "C. Giottoli. D. Bosi (RnS)" },
    { titolo: "Cristo Gesù speranza delle genti", autore: "G. M. Attinà (RnS)" },
    { titolo: "Cristo Gesù, Salvatore", autore: "E. Costa (Musica Trad. Occitana)" },
    { titolo: "Cristo Re", autore: "Nicola Montuori (RnS)" },
    
    { titolo: "Dall'aurora al tramonto", autore: "Balduzzi e Casucci" },
    { titolo: "Danza del fiore rosso", autore: "Canto Lupetti" },
    { titolo: "Danza la vita", autore: "Canto Scout" },
    { titolo: "Davanti a questo amore", autore: "De Luca, Marranzino, Conte" },
    { titolo: "Davanti a Te", autore: "GianLuigi Serapiglia" },
    { titolo: "Davanti al Re", autore: "Steven Fry" },
    { titolo: "Del nostro meglio", autore: "Canto Lupetti" },
    { titolo: "Dell'aurora tu sorgi più bella", autore: "L. Guida F.S.M. d'Aria" },
    { titolo: "Di notte a mezzanotte", autore: "Canto popolare Anonimo" },
    { titolo: "Di stelle d'angeli", autore: "Canto popolare Anonimo" },
    { titolo: "Din Don Dan Completa", autore: "Jingle Bells" },
    { titolo: "Dio aprirà una via", autore: "Matteo Mori" },
    { titolo: "Dio è amore", autore: "RnS" },
    { titolo: "Dio ha tanto amato il mondo", autore: "(RnS) A. De Luca, B. Conte" },
    { titolo: "Dio per amico", autore: "Paolo Auricchio" },
    { titolo: "Dio si è fatto come noi", autore: "Marcello Giombini (musica) e Gino Stefani (testo) 1967" },
    { titolo: "Dolce Sentire (Fratello Sole)", autore: "Ritz Ortolani" },
    { titolo: "Dona la pace", autore: "Figli del Divino Amore" },
    { titolo: "Dove Tu sei", autore: "Gen Rosso" },
    
    { titolo: "E la strada di apre", autore: "Gen Arcobaleno" },
    { titolo: "E sono solo un uomo", autore: "Don Pierangelo Sequeri 1978" },
    { titolo: "E susi pasturi", autore: "Carlo Muratori" },
    { titolo: "E' bello lodarti", autore: "Gen Verde" },
    { titolo: "E' bello", autore: "Gen Rosso" },
    { titolo: "E' di nuovo Route", autore: "Canto scout" },
    { titolo: "E' gioia per me", autore: "Kenosis" },
    { titolo: "E' la festa di Natale", autore: "A.M. Galliano, D. Semprini" },
    { titolo: "E' Natale Forza venite Gente", autore: "M.Castellacci,  R. Biagioli, M.: M.Paulicelli, G. De Matteis, G. Belardinelli" },
    { titolo: "E'giunta l'ora", autore: "L. Scaglianti" },
    { titolo: "Ecco il nostro SI!", autore: "Emanuele Fossi" },
    { titolo: "Ecco lo sposo", autore: "Frà Giuseppe Di Fatta" },
    { titolo: "Ecco Maggio", autore: "" },
    { titolo: "Ecco quel che abbiamo", autore: "(Il miracolo del pane) Gen verde" },
    { titolo: "Eccomi Gesù", autore: "Gen verde" },
    { titolo: "Eccomi", autore: "Don Marco Frisina" },
    { titolo: "Effonderò il mio Spirito", autore: "Don Marco Frisina" },
    { titolo: "Emmanuel - Kenosis", autore: "Fra' Massimo Corallo" },
    { titolo: "Emmanuel Tu sei", autore: "Francesco Buttazzo" },
    { titolo: "Era lì", autore: "Gabriella Di Lena" },
    { titolo: "Evenu Shalom alejem", autore: "Canto ebraico XVI sec." },
    
    { titolo: "Fa'ch'io creda", autore: "Alessandra Di Luca, Benedetto Conte (RnS)" },
    { titolo: "Facci nuovi con Te", autore: "" },
    { titolo: "Figliol Prodigo - Abbracciami Gesù", autore: "Figli del Divino Amore" },
    { titolo: "Fissa gli occhi", autore: "Franco Costantini" },
    { titolo: "Fratello sole sorella luna (Dolce Sentire )", autore: "Ritz Ortolani" },
    { titolo: "Fratello Sole", autore: "Ritz Ortolani" },
    { titolo: "FruttoDellaNostraTerra", autore: "Francesco Buttazzo 2000" },
    
    { titolo: "Gesù è la pace", autore: "RnS Kandela Groves" },
    { titolo: "Gesù e la samaritana", autore: "A. De Luca, B. Conte" },
    { titolo: "Gesù per le strade", autore: "D. Bosi 2006" },
    { titolo: "Gesù verrà", autore: "RnS B. Daniele" },
    { titolo: "Giorno di concordia", autore: "Gen Verde" },
    { titolo: "Giovane donna", autore: "Scaglianti Bancolini" },
    { titolo: "Gloria a Dio nell'alto dei cieli", autore: "Guglielmo Amidei 1978" },
    { titolo: "Gloria a Dio Serapiglia", autore: "GianLuigi Serapiglia" },
    { titolo: "Gloria Giombini", autore: "Marcello Giombini 1970" },
    { titolo: "Gloria in excelsis Deo", autore: "Lecot" },
    { titolo: "Gloria Kenosis", autore: "Fra Vittorio Avveduto da - Kenosis-  2007" },
    { titolo: "Gloria nell'alto dei cieli", autore: "Gen Verde da Cerco il tuo volto" },
    { titolo: "Gloria San Francesco", autore: "?" },
    { titolo: "Gloria Voce del mio canto", autore: "Gen Rosso" },
    { titolo: "Glorifichiamo il Tuo nome", autore: "RnS" },
    { titolo: "Grande Sei, o mio Signor", autore: "Rinnovamento nello Spirito Santo" },
    { titolo: "Grandi cose", autore: "Gen Rosso" },
    { titolo: "Grazie Mamma", autore: "Gen Rosso" },
    
    { titolo: "Hai dato un cibo", autore: "Anonimo 1670" },
    
    { titolo: "I cieli narrano", autore: "Don Marco Frisina" },
    { titolo: "I fratelli della Jugla", autore: "Canto Scout L/C" },
    { titolo: "I Ponti", autore: "Gen Verde" },
    { titolo: "I segni dei fratelli", autore: "Canto Scout L/C" },
    { titolo: "Il 13 Maggio", autore: "Anonimo" },
    { titolo: "Il Canto dell'Amicizia", autore: "Canto Scout" },
    { titolo: "Il Canto dell'Amore", autore: "Fra Federico Russo" },
    { titolo: "Il cielo è con noi", autore: "Gen Rosso" },
    { titolo: "Il Fuoco della Pasqua", autore: "Antonio Parisi, Anna Maria Galliano" },
    { titolo: "Il giorno e le stagioni", autore: "Enzo Caruso Canto Scout" },
    { titolo: "Il mio canto per te (Tu sei prezioso per Dio)", autore: "Piera Cori" },
    { titolo: "Il mio respiro", autore: "Gen Verde" },
    { titolo: "Il nome di Maria", autore: "Fra' Giuseppe Di Fatta" },
    { titolo: "Il pane del cammino", autore: "Motta, Sequeri" },
    { titolo: "Il Pane", autore: "Stefano Pianori" },
    { titolo: "Il pastore Buono", autore: "fra' Giuseppe Di Fatta" },
    { titolo: "Il seme del Tuo campo", autore: "Gen Rosso, Verde" },
    { titolo: "Il Signore ci ha amato", autore: "Anonimo" },
    { titolo: "Il Signore è il mio Pastore", autore: "Salmo 22 - David Maria Turoldo, Ismaele Passoni" },
    { titolo: "Il Signore è la Luce", autore: "Marcello Giombini" },
    { titolo: "Il Signore è la mia salvezza - Cantico dei redenti", autore: "Alberto Marani" },
    { titolo: "Il Signore in eterno", autore: "Anonimo" },
    { titolo: "Il Tuo Amore, Signore per noi", autore: "Scaglianti" },
    { titolo: "Immacolata, Vergine bella", autore: "Pietro Panzetti" },
    { titolo: "In Comunione (Signore Ti ringrazio perché)", autore: "Stefano Pianori" },
    { titolo: "In Famiglia", autore: "Gen Verde" },
    { titolo: "In Squadriglia", autore: "Canto Scout" },
    { titolo: "Infinitamente grazie", autore: "A. De Luca, P. Pier Aguila" },
    { titolo: "Inni e canti", autore: "F. Tavoni" },
    { titolo: "Inno a San Giuseppe", autore: "Anonimo" },
    { titolo: "Inno a San Luigi Primi vespri", autore: "Anonimo" },
    { titolo: "Inno a San Luigi", autore: "Anonimo" },
    { titolo: "Inno a Santa Lucia", autore: "Carmelo Liggeri (M.) Giovanni Maria D'Asta (T.)" },
    { titolo: "Inno al Sacro Cuore Brocato", autore: "Brocato" },
    { titolo: "Inno al Sacro Cuore", autore: "Anonimo" },
    { titolo: "Inno alla carità", autore: "Fabio Baggio" },
    { titolo: "Inno alla Misericordia", autore: "Don Carlo Colafranceschi" },
    { titolo: "Inno Giubileo 2000", autore: "J.P. Lècot" },
    { titolo: "Inno GMG Lisbona 2023", autore: "HÁ PRESSA NO AR - João Paulo Vaz, Pedro Ferreira. Adatt. Valerio Lode Ciprì" },
    { titolo: "Invochiamo la Tua presenza", autore: "Figli del Divino Amore" },
    { titolo: "Io sento la Tua voce", autore: "Anonimo o tradizionale?" },
    { titolo: "Io sono con te", autore: "Rinnovamento nello Spirito Santo" },
    { titolo: "Io vedo il Re", autore: "Rinnovamento nello Spirito Santo" },
    { titolo: "Io vedo la Tua luce Symbolum '79", autore: "Pierangelo Sequeri" },
    
    { titolo: "Jubilate Deo", autore: "Taize'" },
    
    { titolo: "Kayre Marya", autore: "Paolo Spoladore" },
    { titolo: "Kirie Eleison Tu sempre accoglierai", autore: "Gen Rosso" },
    
    { titolo: "L'acqua, la terra, il cielo", autore: "Canto Scout" },
    { titolo: "L'Emmanuel Ridotta", autore: "GMG 2000" },
    { titolo: "L'Emmanuel", autore: "GMG 2000" },
    { titolo: "L'ultima sera", autore: "Gen Rosso" },
    { titolo: "L'unico Maestro", autore: "Matteo Civico" },
    { titolo: "La casa", autore: "Gen Rosso 1969" },
    { titolo: "La luce vedrà", autore: "Chris Rice (Continentals)" },
    { titolo: "La Meridiana", autore: "Enzo Caruso Canto Scout" },
    { titolo: "La mia anima canta", autore: "Gen Verde" },
    { titolo: "La mia Pasqua è il Signore", autore: "Anna Maria Galliano (T.) Rino Farruggio (M.)" },
    { titolo: "La mia vita è Cristo", autore: "(M) Angelo Di Mario; (T) Carlo Recalcati" },
    { titolo: "La nuova alleanza", autore: "?" },
    { titolo: "La pelle di Dio", autore: "A. Costa P. Marchetti - Canto Scout" },
    { titolo: "La piroga", autore: "Canto Scout" },
    { titolo: "La stagione della caccia", autore: "Canto Scout L/C" },
    { titolo: "La Trasfigurazione", autore: "Don Marco Frisina" },
    { titolo: "La Tua alleanza", autore: "Don E. Niviaggi e M. Lieggi" },
    { titolo: "La Tua gloria", autore: "Mirko e Giorgia" },
    { titolo: "La vera gioia", autore: "Don Marco Frisina" },
    { titolo: "La vera vite", autore: "Don Marco Frisina" },
    { titolo: "Lampada ai miei passi", autore: "Marco Mellino" },
    { titolo: "Lascia che dentro te", autore: "GAM" },
    { titolo: "Laudato sii", autore: "Paulicelli? 1981" },
    { titolo: "Le Tue Meraviglie", autore: "Chiara Casucci, Mite Balduzzi" },
    { titolo: "Lodate Dio, schiere beate", autore: "Dusan Stefani, Gianluigi Rusconi" },
    { titolo: "Lodate Dio", autore: "Gen Rosso" },
    { titolo: "Lodate il Signore dai cieli", autore: "Don Marco Frisina" },
    { titolo: "Lodate il Signore", autore: "RnS" },
    { titolo: "Lode a Te, o Cristo", autore: "Gen Verde" },
    { titolo: "Lode a Te, Signor", autore: "Andy Carter" },
    { titolo: "Lode a Te, Signore Gesù", autore: "F. Meneghello" },
    { titolo: "Lode e onore a Te_DO", autore: "D. Anselmi" },
    { titolo: "Lode e onore a Te_SignoreGesu", autore: "?" },
    { titolo: "Lode e onore a Te", autore: "?" },
    { titolo: "Lodi all'Altissimo", autore: "Don Marco Frisina" },
    { titolo: "Luce del mondo (Sono qui a lodarTi)", autore: "RnS" },
    { titolo: "Lui verrà e ti salverà", autore: "Bob Fitts e Gary Sadler RnS 1999" },
    { titolo: "Lui", autore: "La vera Fede - Canto Scout" },

    { titolo: "Madonna delle lacrime", autore: "C. Liggeri" },
    { titolo: "Madonnina dai riccioli d'oro", autore: "I Girasoli 1997" },
    { titolo: "Madre della speranza Ridotta", autore: "Chiara Bizzetti" },
    { titolo: "Madre della speranza", autore: "Chiara Bizzetti" },
    { titolo: "Madre dolcissima", autore: "Gen Rosso" },
    { titolo: "Madre tu sei", autore: "Fra' G. Di Fatta" },
    { titolo: "Magnifica il Signore anima mia", autore: "Guglielmo Amadei" },
    { titolo: "Magnificat Ravel_Cilia", autore: "Cilia" },
    { titolo: "Magnificat Taizé", autore: "J. Bethier" },
    { titolo: "Mamma del cielo", autore: "Canto Scout L/C" },
    { titolo: "Maranathà", autore: "Don Marco Frisina" },
    { titolo: "Marcia Nuziale Wagner 2", autore: "da 'Lohengrin' R. Wagner" },
    { titolo: "Marcia Nuziale Wagner", autore: "da 'Lohengrin' R. Wagner" },
    { titolo: "Maria (Quando l'Amor)", autore: "Gen Rosso" },
    { titolo: "Maria tu che hai atteso", autore: "Daniele Semprini" },
    { titolo: "Maria tu porta dell'avvento", autore: "A. Galliano, D. Semprini" },
    { titolo: "Maria tu sei", autore: "Gen Rosso" },
    { titolo: "Mio Dio mi abbandono a Te", autore: "Rinnovamento nello Spirito Santo" },
    { titolo: "Mio rifugio sei Tu", autore: "Nicola MonTuori (RnS)" },
    { titolo: "Mira il tuo popolo", autore: "S. Alfonso de' Liguori" },

    { titolo: "Nasce l'amor", autore: "Gen Rosso" },
    { titolo: "Nel tuo silenzio", autore: "Gen" },
    { titolo: "Noi canteremo gloria a Te", autore: "ouis Bourgeois Salterio Ginevrino 1510-1560" },
    { titolo: "Noi con Te", autore: "F. Buttazzo A. Beltrami" },
    { titolo: "Noi Ti lodiam", autore: "(T.) Antonio Gazzera, (M.) Piero Damilano" },
    { titolo: "Noi veglieremo", autore: "Domenico Marchetta" },
    { titolo: "Noi veniamo a Te (Messa Gen)", autore: "GEN Rosso 1972" },
    { titolo: "Noi veniamo a te_Completa", autore: "Francesco Buttazzo" },
    { titolo: "Nome dolcissimo", autore: "Andrea Castelli 1972" },
    { titolo: "Non spegnere l'amore", autore: "Pino Fanelli" },
    { titolo: "Non temere", autore: "Don Marco Frisina" },
    { titolo: "Nozze a Cana", autore: "RnS" },
    
    { titolo: "O bella mia speranza", autore: "Lorenzo Perosi / S. Alfonso" },
    { titolo: "O Dio dell'universo", autore: "Filisetti, Zardini" },
    { titolo: "O fonte dell'Amore", autore: "Techner; Rossi" },
    { titolo: "O Maria Santissima", autore: "Tradiz. V. Meloni; arr. D. Stefani" },
    { titolo: "Offerta di vita", autore: "Fra' G. Di Fatta" },
    { titolo: "Ogni cosa nuova fai", autore: "Fra' G. Di Fatta" },
    { titolo: "Ogni mia parola", autore: "Gen Verde (Isaia 55)" },
    { titolo: "Oh Gesù", autore: "Giaculatoria di Anonimo" },
    { titolo: "Ora che sei in mezzo a noi", autore: "Gianluigi Serapiglia" },
    { titolo: "Ora è tempo di gioia", autore: "Gen Rosso" },
    { titolo: "Ora siamo arrivati", autore: "GianLuigi Serapiglia" },
    { titolo: "Osanna al figlio di David", autore: "Gazzera, Agamennone, Damilano" },
    { titolo: "Osanna all'Altissimo", autore: "Carl Tuihe" },
    { titolo: "Osanna eh!", autore: "Tradizionale Zairese" },
    
    { titolo: "Pace a te fratello mio completa", autore: "Marcello Giombini" },
    { titolo: "Pace a te fratello mio", autore: "Marcello Giombini" },
    { titolo: "Pace a te Serapiglia", autore: "GianLuigi Serapiglia" },
    { titolo: "Pace e Agnello", autore: "Marcello Giombini" },
    { titolo: "Pace è in Te, Signor", autore: "Rinnovamento nello Spirito Santo - Salvatore Martinez - G. Ferrante - Beny Conte" },
    { titolo: "Pace sia, Pace a voi", autore: "Gen Verde" },
    { titolo: "Padre Nostro Giombini NUOVO", autore: "Marcello Giombini" },
    { titolo: "Pane dei poveri (Sazierò di pane)", autore: "Salmo 131" },
    { titolo: "Pane del cielo", autore: "Gen Rosso" },
    { titolo: "Pane di vita nuova COMPLETO", autore: "Don Marco Frisina" },
    { titolo: "Pane di vita nuova", autore: "Don Marco Frisina" },
    { titolo: " Pane di vita Sei", autore: "F. Marranzino – F. Pesare" },
    { titolo: "Passa questo mondo", autore: "(Solo chi ama) - Domenico Machetta 1978" },
    { titolo: "Per sempre canterò il Tuo amore", autore: "Cammino di Santità" },
    { titolo: "Perché Tu sei con me", autore: "Gen Verde" },
    { titolo: "Popoli tutti acclamate", autore: "Rinnovamento nello Spirito Santo (RnS) Darlene Zschech 1993" },
    { titolo: "Preghiera dei poveri di Jahvè (O cieli piovete dall'alto)", autore: "Guglielmo Amadei" },
    { titolo: "Prendimi per mano", autore: "Don Giosy Cento (Servi di Gesù)" },
    { titolo: "Primo Amore", autore: "Nuovi convertiti - Corrado Salmè" },
    { titolo: "Proteggi Tu il mio cammino", autore: "Giovanni Mareggini (IDML -Istituto Diocesano di Musica e Liturgia) 2018" },
    
    { titolo: "Quale gioia è star con te Gesù", autore: "Rinnovamento nello Spirito" },
    { titolo: "Quando busserò", autore: "Marcello Giombini" },
    { titolo: "Quando cammino per il mondo", autore: "Marcello Giombini" },
    { titolo: "Quando venne la Sua ora", autore: "D. Machetta" },
    { titolo: "Quanta sete nel mio cuore", autore: "G. Stefani (Salterio ginevrino)" },
    { titolo: "Quelli che amano Te", autore: "A.R.Amuchàstegui (Gen Rosso)" },
    { titolo: "Questa preghiera", autore: "Mario Piatti" },
    { titolo: "Questo è il mio comandamento", autore: "Don Marco Frisina" },

    { titolo: "Re dei Re", autore: "E. Munda - G. Pretto - L. Christille (RnS)" },
    { titolo: "Re di gloria", autore: "F. Marranzino A. De Luca" },
    { titolo: "Regina Coeli", autore: "Gregoriano" },
    { titolo: "Regina del Cielo, rallegrati", autore: "Francesco Buttazzo" },
    { titolo: "Resta accanto a me", autore: "Gen Verde" },
    { titolo: "Resta con noi Cristo Gesù", autore: "Gianluigi Serapiglia" },
    { titolo: "Resta con noi Signore, alleluja", autore: "(T.) A. Gazzera, (M. e A.) P. Damilano" },
    { titolo: "Resta qui con noi", autore: "Gen Rosso" },
    { titolo: "Resto con Te", autore: "Gen Verde" },
    { titolo: "Rimanete in me", autore: "Rinnovamento nello Spirito" },
    { titolo: "Risurrezione", autore: "Gen Rosso" },
    
    { titolo: "Sacro Cuore di Gesù", autore: "Roland Patzleiner (Figli del Divino Amore)" },
    { titolo: "Saldo è il mio cuore", autore: "E. Remigi - A. Martinez" },
    { titolo: "Salmo_145", autore: "Salmo 145" },
    { titolo: "Salve o dolce vergine", autore: "Don Marco Frisina" },
    { titolo: "Salve Regina", autore: "Gen Verde" },
    { titolo: "San Damiano", autore: "Riz Ortolani - Benjamin" },
    { titolo: "Santa Maria del cammino", autore: "Juan Antonio Espinosa/Renato D'Andrea 1971" },
    { titolo: "Santo (Come fuoco vivo)", autore: "Gen Rosso/Verde" },
    { titolo: "Santo Bonfitto", autore: "M. Bonfitto" },
    { titolo: "Santo Buttazzo", autore: "Francesco Buttazzo" },
    { titolo: "Santo Gen", autore: "Gen Rosso/Verde" },
    { titolo: "Santo il Signore Dio", autore: "Daniele Ricci" },
    { titolo: "Santo Kenosis", autore: "Fra Vittorio Kenosis, Musica Fra Massimo Corallo" },
    { titolo: "Santo San Francesco", autore: "San Francesco" },
    { titolo: "Santo Serapiglia", autore: "GianLuigi Serapiglia" },
    { titolo: "Santo Spirito, vieni", autore: "Rinnovamento nello Spirito Santo" },
    { titolo: "Santo Voce del mio canto", autore: "Gen Rosso" },
    { titolo: "Sazierò di pane (Pane dei poveri)", autore: "??" },
    { titolo: "Scusa Signore", autore: "Biagioli, Aliscioni" },
    { titolo: "Se m'accogli", autore: "Pierangelo Sequeri" },
    { titolo: "Segni del Tuo amore", autore: "Gen Verde-Rosso" },
    { titolo: "Sei il mio dolce Pastore", autore: "Salmo 22 Vaccaro" },
    { titolo: "Sei il mio rifugio", autore: "Rinnovamento nello Spirito" },
    { titolo: "Sei per noi cibo di verità", autore: "Rinnovamento nello Spirito" },
    { titolo: "Sei Tu Signore il mio Pastor", autore: "R. Jef 1956" },
    { titolo: "Sei Tu Signore il Pane", autore: "Kirbie" },
    { titolo: "Sei Tu Signore", autore: "Francesco Buttazzo" },
    { titolo: "Seme dell'eternità", autore: "Gen Verde" },
    { titolo: "Semina la pace", autore: "Gen Rosso" },
    { titolo: "Servire è regnare", autore: "Gen Verde" },
    { titolo: "Servo per Amore", autore: "Gen Rosso" },
    { titolo: "Si accende una luce", autore: "Novena di Natale" },
    { titolo: "Signor, Tu Sei la luce", autore: "Salmo 25?" },
    { titolo: "Signora dolce, Ave", autore: "Don Gaetano Tantalo" },
    { titolo: "Signore ascolta, Padre perdona", autore: "G. Stefani" },
    { titolo: "Signore ci nutri alla Tua mensa", autore: "Francesco Buttazzo" },
    { titolo: "Signore Ti ringrazio perché (In Comunione)", autore: "Stefano Pianori" },
    { titolo: "Signore Ti ringrazio perché Foglio", autore: "Foglio" },
    { titolo: "Signore Ti ringrazio perché Mamma Carmela", autore: "Mamma Carmela" },
    { titolo: "Signore, abbi pietà di noi", autore: "GianLuigi Serapiglia" },
    { titolo: "Signore, com'è bello", autore: "(Le Tende)- Claudio Chieffo" },
    { titolo: "Signore, Sei Tu il mio pastor", autore: "R. Jef (Stefani?)" },
    { titolo: "So che Sei qui", autore: "Gen Verde" },
    { titolo: "So che Tu sei il mio Signor", autore: "RnS" },
    { titolo: "Sognando sogni grandi_SPICE", autore: "Gen Verde Gruppo canto SPICE" },
    { titolo: "Solo Grazie", autore: "Figli del Divino Amore" },
    { titolo: "Sono qui a lodarTi", autore: "Rinnovamento nello Spirito Santo" },
    { titolo: "Sorgi, Signore e salvaci", autore: "Damilano" },
    { titolo: "Spirito del Dio vivente", autore: "Rinnovamento nello Spirito Santo - Jacques Godard" },
    { titolo: "Spirito di Dio", autore: "Rangani, Soldano" },
    { titolo: "Stai con me", autore: "Rinnovamento nello Spirito Santo - Ruben Morgan" },
    { titolo: "Strade e pensieri per domani", autore: "Canto Scout  Matteo Civico" },
    { titolo: "Su ali d'aquila", autore: "padre Jan Michael Joncas (RnS)" },
    { titolo: "Su questo altare", autore: "Paolo Auricchio" },
    { titolo: "Svegliati, Svegliati Sion", autore: "Rinnovamento nello Spirito Santo (RnS) 1992" },
    { titolo: "Symbolum '79 (Io vedo la Tua luce)", autore: "Pierangelo Sequeri" },
    
    { titolo: "T'amerò Signor", autore: "Rinnovamento nello Spirito Santo" },
    { titolo: "TanGram", autore: "Paolo Favotti - Canto Scout 2023" },
    { titolo: "Te al centro del mio cuore", autore: "" },
    { titolo: "Te Lodiamo Trinità", autore: "G. Stefani" },
    { titolo: "Tempo di ricominciare", autore: "Gen Verde 2012" },
    { titolo: "Ti adoro, o mio Signor", autore: "Rinnovamento nello Spirito Santo" },
    { titolo: "Ti amo Signor", autore: "Rinnovamento nello Spirito Santo" },
    { titolo: "Ti loderò,ti adorerò, ti canterò", autore: "Rinnovamento nello Spirito Santo - Domenico Basta, Rossella Baldi" },
    { titolo: "Ti lodino i popoli Dio", autore: "Francesco Buttazzo" },
    { titolo: "Ti ringrazio o mio Signore", autore: "Cesareo Gabarain" },
    { titolo: "Ti salutiamo, Vergine", autore: "Anonimo" },
    { titolo: "Ti saluto o Croce Santa", autore: "(T.) Andrea Gazzera, (M.) Piero Damilano" },
    { titolo: "Ti seguirò", autore: "Don Marco Frisina" },
    { titolo: "Toccami", autore: "Dylan Varriale" },
    { titolo: "Tornerà il Signor", autore: "Rinnovamento nello Spirito" },
    { titolo: "Tu festa della Luce", autore: "O. Muller 1825, G.F.Poma" },
    { titolo: "Tu sarai profeta", autore: "Don Marco Frisina" },
    { titolo: "Tu scendi dalle stelle", autore: "Sant'Alfonso Maria de' Liguori 1755" },
    { titolo: "Tu sei (Soffierà)", autore: "Paolo Spoladore" },
    { titolo: "Tu Sei come roccia", autore: "D.F. Poma , C. Goudimel" },
    { titolo: "Tu Sei la mia vita (Symbolum '77)", autore: "Pierangelo Sequeri" },
    { titolo: "Tu sei prezioso per Dio (il mio canto per te)", autore: "Piera Cori" },
    { titolo: "Tu Sei qui", autore: "Rinnovamento nello Spirito / Adattamento di Way Maker di Sinach 2009" },
    { titolo: "Tu Sei Re", autore: "S. Sciacca G. Pitruzzella (RnS)" },
    { titolo: "Tu sole vivo", autore: "E. Renoglio 1980-90" },
    { titolo: "Tu, quando verrai", autore: "W. Croft 1678, G.F.Poma A. Fant" },
    { titolo: "Tutta la terra canti a Dio", autore: "L. Bougeois 1510-1591, A. Albisetti 1973" },
    { titolo: "Tutti per uno", autore: "RnS" },
    
    { titolo: "Vaga Aurora", autore: "Nenia natalizia - Rielab. Emanuele Carpanzano" },
    { titolo: "Veniamo da Te, o Signore", autore: "M. T. Henderson" },
    { titolo: "Venite applaudiamo al Signore", autore: "Don Marco Frisina" },
    { titolo: "Venite fedeli", autore: "Trascr. J. F. Wade" },
    { titolo: "Verbum Panis", autore: "(M.) Giampietro (Mite) Balduzzi, (T.) Chiara Casucci" },
    { titolo: "Vergin Maria che fulgida", autore: "Anonimo" },
    { titolo: "Verso di Te", autore: "Gen Rosso" },
    { titolo: "Vi darò un cuore nuovo", autore: "G. Amadei" },
    { titolo: "Viaggio nella vita", autore: "Don Giosy Cento (Servi di Gesù)" },
    { titolo: "Vieni dal Libano", autore: "P. Marciani - N. Cometto" },
    { titolo: "Vieni e seguimi", autore: "Gen Rosso" },
    { titolo: "Vieni Fratello", autore: "A. Lagorio" },
    { titolo: "Vieni Santo Spirito", autore: "Gen Verde" },
    { titolo: "Vieni Spirito forza dall'alto", autore: "Figli del Divino Amore" },
    { titolo: "Vieni, o Signor", autore: "Damilano" },
    { titolo: "Viva il Sacro Cuore", autore: "Anonimo" },
    { titolo: "Vivere la vita", autore: "Gen Verde" },
    { titolo: "Vocazione", autore: "Gen Rosso" },
    { titolo: "Voce del mio canto", autore: "Gen Rosso" },
    { titolo: "Voglio adorare Te", autore: "Rinnovamento nello Spirito Santo - Savio De Filippis, Francesco Frigiola" },
    { titolo: "Voglio stare con Te", autore: "Nuovi convertiti - Corrado Salmè" },
    { titolo: "Voglio tornar da mio Padre", autore: "Anonimo" },

    { titolo: "We shall overcome", autore: "Peter Seeger/Joan Baets, Reverend Charles Tindley of Philadelphia 1903" },

    { titolo: "Yesterday", autore: "The Beatles da 'Help!' 1965" }
        
];