// Il Catalogo centralizzato delle canzoni con gli autori
const catalogoCanzoni = [
    { titolo: "4 Marzo 43", autore: "Lucio Dalla - Sanremo 1971" },
    { titolo: "29 Settembre", autore: "Lucio Battisti" },

    { titolo: "A day in The Life", autore: "The Beatles" },
    { titolo: "A me me piace o blues", autore: "Pino Daniele da 'Nero a metà' 1980" },
    { titolo: "A rush of blood to the head", autore: "Coldplay da 'A Rush of blood to the head' 2002" },
    { titolo: "A te", autore: "Jovanotti da 'Safari' 2008" },
    { titolo: "A testa in giu", autore: "Pino Daniele da  'Nero a metà' 1980" },
    { titolo: "A Whisper", autore: "Coldplay da 'A Rush of blood to the head' 2002" },
    { titolo: "Acqua azzurra acqua chiara", autore: "Lucio Battisti da 'Lucio Battisti' 1969" },
    { titolo: "Acquarious", autore: "Jame Rado da 'Hair' 1969 " },
    { titolo: "Al cinema", autore: "Lucio Battisti da 'Una donna per amico' 1978" },
    { titolo: "Albachiara", autore: "Vasco Rossi" },
    { titolo: "Alice non lo sa", autore: "Francesco De Gregori da 'Alice non lo sa' 1973" },
    { titolo: "All I want is you", autore: "U2 da  'Rattle and Hum' 1988" },
    { titolo: "All you need is Love", autore: "The Beatles 1967" },
    { titolo: "Alleria", autore: "Pino Daniele da  'Nero a metà' 1980" },
    { titolo: "Almeno credo", autore: "Luciano Ligabue da  'Miss Mondo' 1999" },
    { titolo: "Always in my head", autore: "Coldplay da 'Ghost stories' 2014" },
    { titolo: "Amarsi un po", autore: "Lucio Battisti da 'Io tu noi tutti' 1977"},
    { titolo: "Ami ancora Elisa", autore: "Lucio Battisti da 'Io tu noi tutti' 1977" },
    { titolo: "Amici mai", autore: "Antonello Venditti da 'Benvenuti in paradiso' 1991" },
    { titolo: "Amico di ieri", autore: "Le Orme da 'Smogmagica' 1975" },
    { titolo: "Amor mio", autore: "Battisti-Mogol per Mina 1971" },
    { titolo: "Amore bello", autore: "Claudio Baglioni  1973" },
    { titolo: "Amore che vieni amore che vai", autore: "Fabrizio de Andrè 'Tutto De Andrè' 1966" },
    { titolo: "Amore mio di provincia", autore: "Lucio Battisti da 'Una giornata uggiosa' 1980" },
    { titolo: "Amsterdam", autore: "Coldplay da 'A Rush of blood to the head' 2002" },
    { titolo: "Anche per te", autore: "Lucio Battisti da 'Lucio Battisti' 1969" },
    { titolo: "Ancora in piedi", autore: "Luciano Ligabue da 'Sopravvissuti e sopravviventi'1993" },
    { titolo: "Ancora noi", autore: "Luciano Ligabue da 'Start' 2019" },
    { titolo: "Ancora tu", autore: "Lucio Battisti da 'La batteria il contrabbasso etc.' 1976" },
    { titolo: "Ancora", autore: "Eduardo De Crescenzo da 'Sanremo' 1981" },
    { titolo: "Andare per andare", autore: "PFM da 'Ulisse' 1997" },
    { titolo: "Anema e core", autore: "(Testo) Tito Manlio '(Musica) Salve D'Esposito 1950" },
    { titolo: "Angelo della nebbia", autore: "Luciano Ligabue da 'Ligabue' 1990" },
    { titolo: "AnimaMia", autore: "Cugini di campagna 1973" },
    { titolo: "Anime in plexigass", autore: "Luciano Ligabue da 'Lambrusco rose & popcorn' 1991" },
    { titolo: "Anna e Marco", autore: "Lucio Dalla da 'Lucio Dalla' 1979" },
    { titolo: "Anna", autore: "Lucio Battisti da 'Emozioni' 1970" },
    { titolo: "Annarè", autore: "PinoDaniele da 'Bella 'Mbriana' 1982" },
    { titolo: "Applausi", autore: "Camaleonti  1967" },
    { titolo: "Appocundria", autore: "Pino Daniele da 'Nero a metà' 1980" },
    { titolo: "Arrivederci a questa sera", autore: "Lucio Battisti da 'Una giornata uggiosa' 1980" },
    { titolo: "As the deer", autore: "Martin J. Nystrom 1984" },
    { titolo: "Atlas", autore: "Coldplay da soundTrack 'Hunger Games' 2013" },
    { titolo: "Atto di fede", autore: "Luciano Ligabue da 'Arrivederci mostro!' 2010" },
    { titolo: "Aver paura di innamorarsi troppo", autore: "Lucio Battisti da 'Una donna per amico' 1978" },
    { titolo: "Azzurro", autore: "Adriano Celentano" },

    { titolo: "Babbo in prigione", autore: "Francesco De Gregori da 'De Gregori' 1978" },
    { titolo: "Balla Linda", autore: "Lucio Battisti' 1968" },
    { titolo: "Balliamo sul mondo", autore: "Luciano Ligabue da 'Ligabue' 1990" },
    { titolo: "Bandiera bianca", autore: "Franco Battiato da 'La voce del padrone' 1981" },
    { titolo: "Beautiful day", autore: " U2 da 'All That You Can't Leave Behind' 2000" },
    { titolo: "Bella 'mbriana", autore: "Pino Daniele da 'Bella 'Mbriana' 1982" },
    { titolo: "Bella senz'anima", autore: "Ricardo Cocciante da 'Anima' 1974" },
    { titolo: "Bianco Natale", autore: "B. Chrosby Irving Berlin 1940" },
    { titolo: "Blowin' in the Wind", autore: "Bob Dylan" },
    { titolo: "Bollicine", autore: "Vasco Rossi da 'Bollicine' 1983" },
    { titolo: "Bomba o non bomba", autore: "Antonello Venditti da 'Sotto il segno dei pesci' 1978" },
    { titolo: "Brain damage", autore: "Pink Floyd da 'The dark side of the moon' 1973" },
    { titolo: "Breathe", autore: "Pink Floyd da 'The dark side of the moon' 1973" },
    { titolo: "Buonanotte fiorellino", autore: "Francesco De Gregori da 'Rimmel' 1975" },

    { titolo: "C'è chi dice no", autore: " Vasco Rossi da 'C'è chi dice no' 1987" },
    { titolo: "C'è la luna 'mmienz'o mari", autore: "Popolare siciliano 1927" },
    { titolo: "Cara", autore: "Lucio Dalla da 'Dalla' 1980" },
    { titolo: "Caruso", autore: "Lucio Dalla da 'DallAmeriCaruso' 1986" },
    { titolo: "Cascare nei tuoi occhi", autore: "Ultimo da 'Peter Pan' 2017" },
    { titolo: "Centro di gravita permanente", autore: "Franco Battiato da 'La voce del padrone' 1981" },
    { titolo: "Certe donne brillano", autore: "Luciano Ligabue da 'Start' 2019" },
    { titolo: "Certe notti", autore: "Luciano Ligabue da 'Buon compeanno Elvis' 1995" },
    { titolo: "Certi notti", autore: "Luciano & Manueli 2016" },
    { titolo: "Chan Chan", autore: "Buena Vista Social Club da 'Buena Vista Social Club' 1997" },
    { titolo: "Che male c'è", autore: "Pino Daniele da 'Dimmi cosa succede sulla terra' 1997" },
    { titolo: "Che te ne fotte", autore: "Pino Daniele da 'Vai mò' 1981" },
    { titolo: "Child in time", autore: "Deep Purple da 'Deep Purple in Rock' 1970" },
    { titolo: "Chissa se in cielo passano gli Who", autore: "Luciano Ligabue da 'Fuori come va?' 2002" },
    { titolo: "Ci sei sempre stata", autore: "Luciano Ligabue da 'Arrivederci mostro!' 2010" },
    { titolo: "Ci vorrebbe un amico", autore: "Antonello Venditti da 'Cuore' 1984" },
    { titolo: "Ciao", autore: "Vasco Rossi da 'C'è chi dice no' 1987" },
    { titolo: "Cio che rimane di noi", autore: "Luciano Ligabue da 'Mondovisione' 2014" },
    { titolo: "Ciuri, ciuri", autore: "Canto Popolare di Francesco Paolo Frontini 1883" },
    { titolo: "Clocks", autore: "Coldplay da 'A Rush of blood to the head' 2002" },
    { titolo: "Com'e profondo il mare", autore: "Lucio Dalla da 'Com'e' profondo il mare' 1977" },
    { titolo: "Come pioveva", autore: "Armando Gill (M. Testa) 1918" },
    { titolo: "Comfortably numb", autore: "Pink Floyd da 'The wall' 1979" },
    { titolo: "Comme facette màmmeta", autore: "Giuseppe Capaldo, Salvatore Gambardella 1906" },
    { titolo: "Compagno di scuola", autore: "Antonello Venditti da 'Lilly' 1975" },
    { titolo: "Comunque bella", autore: "Lucio Battisti da 'Umanamente uomo il sogno' 1972" },
    { titolo: "Con il nastro rosa", autore: "Lucio Battisti da 'Una giornata uggiosa' 1980" },
    { titolo: "Con la scusa del rock'n roll", autore: "Luciano Ligabue da 'Mondovisione' 2014" },
    { titolo: "Confusione", autore: "Lucio Battisti da 'Il mio canto libero' 1972" },
    { titolo: "Cosa sarà", autore: "Lucio Dalla da 'Lucio Dalla' 1979" },
    { titolo: "Cosa vuoi che sia", autore: "Luciano Ligabue da 'Nome e cognome' 2005" },
    { titolo: "Creep", autore: "Radiohead da 'Pablo Honey' 1993" },
    { titolo: "Cu ti lu dissi", autore: "Rosa Ballistreri 1967" },
    { titolo: "Cuccuruccuccu", autore: "Franco Battiato da 'La voce del padrone' 1981" },
    { titolo: "Cuocciu r'Amuri", autore: "Lello Analfino 2014" },
    { titolo: "Cyrano", autore: "Sergio Cammariere, Gino Paoli 2016" },

    { titolo: "Da adesso in poi", autore: "Luciano Ligabue da 'Miss Mondo' 1999" },
    { titolo: "Dammi solo un minuto", autore: "Pooh 1975" },
    { titolo: "Daylight", autore: "Coldplay da 'A Rush of blood to the head' 2002" },
    { titolo: "Dedicato a te", autore: "Le Vibrazioni da 'Le vibrazioni' 2003" },
    { titolo: "Dicitanciello vuie", autore: "Enzo Fusco (T.), Rodolfo Falvo (M.) 1930" },
    { titolo: "Dieci ragazze", autore: "Lucio Battisti 1969" },
    { titolo: "Dio aprira una via", autore: "Matteo Mori" },
    { titolo: "Dio è morto", autore: "Francesco Guccini (Nomadi)" },
    { titolo: "Dio mio no", autore: "Lucio Battisti da 'Amore non amore' 1971" },
    { titolo: "Disperato erotico stomp", autore: "Lucio Dalla da 'Com'è profondo il mare' 1977" },
    { titolo: "Dolce di giorno", autore: "Lucio Battisti 1969" },
    { titolo: "Dolcissima Maria", autore: "PFM da 'L'isola di niente' 1974" },
    { titolo: "Don't Panic", autore: "Coldplay da 'Parachutes' 2000" },
    { titolo: "Donna selvaggia donna", autore: "Lucio Battisti da 'Una donna per amico' 1978" },
    { titolo: "Dont Look Back In Anger", autore: "Oasis '(What's the Story) Morning Glory?' 1996" },
    { titolo: "Dormi giujuzza", autore: "Aurelio Caliri da 'Sicilia primo amore' 2015" },
    { titolo: "Dotti medici e sapienti", autore: "Edoardo Bennato da 'Burattino senza fili' 1977" },
    { titolo: "Dove arriva quel cespuglio", autore: "Lucio Battisti da 'La batteria il contrabbasso etc.' 1976" },
    { titolo: "Due mondi", autore: "Lucio Battisti da 'Anima latina' 1974" },
    { titolo: "Due zingari", autore: "Francesco De Gregori da 'De Gregori' 1978" },
    
    { titolo: "E la chimano estate", autore: "Bruno Martino 1960" },
    { titolo: "E penso a te", autore: "Lucio Battisti da 'Umanamente uomo il sogno' 1972" },
    { titolo: "E piu forte di me", autore: "Luciano Ligabue da 'Nome e cognome' 2005" },
    { titolo: "E se domani", autore: "G. Calabrese e C.A. Rossi per Mina 1964" },
    { titolo: "E so cuntento e sta", autore: "Pino Daniele da 'Nero a metà' 1980" },
    { titolo: "E sono sol un uomo", autore: "Pierangelo Sequeri noto anche (come Symbolum '78)" },
    { titolo: "E ti vengo a cercare", autore: "Franco Battiato da 'Fisiognomica' 1988" },
    { titolo: "E tu", autore: "Claudio Baglioni da 'E tu' 1974" },
    { titolo: "E", autore: "Luciano Ligabue da 'Miss Mondo' 1999" },
    { titolo: "E' stata tua la colpa", autore: "Edoardo Bennato da 'Burattino senza fili' 1977" },
    { titolo: "Earth song", autore: "Michael Jackson 1995" },
    { titolo: "Elena no", autore: "Lucio Battisti da 'Umanamente uomo il sogno' 1972" },
    { titolo: "Emozioni", autore: "Lucio Battisti da 'Emozioni' 1970" },
    { titolo: "Eppur mi son scordato di te", autore: "Lucio Battisti per 'Formula tre' 1971" },
    { titolo: "Eppure soffia", autore: "Pierangelo Bertoli 1976" },
    { titolo: "Era de Maggio", autore: "Franco Battiato da 'Fleurs' 1999" },
    { titolo: "Era inverno", autore: "Le orme da 'Collage' 1971" },
    { titolo: "Eri bellissima", autore: "Luciano Ligabue da 'Fuori come va?' 2002" },
    { titolo: "Eternita", autore: "Camaleonti  da - Sanremo 1970" },
    { titolo: "Everyday life", autore: "Coldplay da 'Everyday Life' 2019" },
    { titolo: "ExitMusic", autore: "Radiohead da sound-track 'Romeo and Juliet' 1996" },

    { titolo: "Father and son", autore: "Cat Stevens  da 'Tea for the Tillerman' 1970" },
    { titolo: "Fiori rosa fiori di pesco", autore: "Lucio Battisti da 'Lucio Battisti' 1969" },
    { titolo: "Fisiognomica", autore: "Franco Battiato da 'Fisiognomica' 1988" },
    { titolo: "Fix You", autore: "Coldplay da 'X & Y' 2000" },
    { titolo: "Fly on", autore: "Coldplay da 'Ghost stories' 2014" },
    { titolo: "Forse mi trovo", autore: "Luciano Ligabue da 'Miss Mondo' 1999" },
    { titolo: "Funiculì funiculà", autore: "Giuseppe Turco (T.), Luigi Denzao (M.) 1880" },
    { titolo: "Fuori come va", autore: "Luciano Ligabue da 'Fuori come va' 2002" },
    { titolo: "Fuoritempo", autore: "Luciano Ligabue da 'A che ora è la fine del mondo?' 1994" },

    { titolo: "GabrielsOboe", autore: "Ennio Morricone da 'Mission' 1986" },
    { titolo: "Gelosa cara", autore: "Lucio Battisti da 'Una giornata uggiosa' 1980" },
    { titolo: "Generale", autore: "Francesco De Gregori da 'De Gregori' 1978" },
    { titolo: "Gioco di bimba", autore: "Le orme da 'Uomo di pezza' 1972" },
    { titolo: "Giorno per giorno", autore: "Luciano Ligabue da 'Nome e cognome' 2005" },
    { titolo: "Giri armonici Maggiore e minore", autore: "Andrea Palma" },
    { titolo: "Gli uccelli", autore: "Franco Battiato da 'La voce del padrone' 1981" },
    { titolo: "Grande grande grande", autore: "T. Renis e ?. Testa per Mina 1971" },
    { titolo: "Grazie Roma", autore: "Antonello Venditti da 'Circo Massimo' 1983" },
    { titolo: "Green Eyes", autore: "Coldplay da 'A Rush of blood to the head' 2002" },

    { titolo: "Hai un momento Dio", autore: "Luciano Ligabue da 'Buon compeanno Elvis' 1995" },
    { titolo: "Hallelujah", autore: "L. Cohen da 'Various Positions' 1984" },
    { titolo: "Happy Christmas", autore: "John Lennon 'War Is Over' 1971" },
    { titolo: "Happy hour", autore: "Luciano Ligabue da 'Nome e cognome' 2005" },
    { titolo: "Have You Seen My Shoes", autore: "Pino Daniele da 'Vai mò' 1981" },
    { titolo: "Heroes", autore: "David Bowie da 'Heroes' 1977" },
    { titolo: "Hey Jude", autore: "Beatles  da 'Hey Jude' 1968" },
    { titolo: "Hey you", autore: "Pink Floyd da 'The wall' 1979" },
    { titolo: "Ho messo via", autore: "Luciano Ligabue da 'Sopravvissuti e sopravviventi' 1993" },
    { titolo: "Ho perso le parole", autore: "Luciano Ligabue da 'RadioFreccia' 1998" },
    { titolo: "Ho un anno di piu", autore: "Lucio Battisti da 'Io tu noi tutti' 1977" },

    { titolo: "I ragazzi sono in giro", autore: "Luciano Ligabue da 'Buon compeanno Elvis' 1995" },
    { titolo: "I say a little prayer", autore: "da 'The Windows Of The World' B. Bacharach 1967" },
    { titolo: "I say i sto cca", autore: "Pino Daniele da 'Nero a metà' 1980" },
    { titolo: "I treni di Tozeur", autore: "Franco Battiato da 'Mondi lontanissimi' 1984" },
    { titolo: "I vavaluci", autore: "Anonimo Popolare Goliardico" },
    { titolo: "Il 56", autore: "Francesco De Gregori da 'De Gregori' 1978" },
    { titolo: "Il ballo delle incertezze", autore: "Ultimo da 'Peter Pan' 2017" },
    { titolo: "Il cielo in una stanza", autore: "Gino Paoli da 'Il cielo in una stanza' 1960" },
    { titolo: "Il cielo", autore: "Renato Zero da 'Zerofobia' 1977" },
    { titolo: "Il gatto e la volpe", autore: "Edoardo Bennato da 'Burattino senza fili' 1977" },
    { titolo: "Il giorno dei giorni", autore: "Luciano Ligabue da 'Nome e cognome' 2005" },
    { titolo: "Il giorno di dolore che uno ha", autore: "Luciano Ligabue da 'Su e giù da un palco' 1997" },
    { titolo: "Il leone e la gallina", autore: "Lucio Battisti da 'Umanamente uomo il sogno' 1972" },
    { titolo: "Il mio canto libero", autore: "Lucio Battisti da 'Il mio canto libero' 1972" },
    { titolo: "Il mio pensiero", autore: "Luciano Ligabue da 'Secondo tempo' 2008" },
    { titolo: "Il mito dell'amore.htm", autore: "Franco Battiato da 'Fisiognomica' 1988" },
    { titolo: "Il mondo che vorrei", autore: "Vasco Rossi 2008" },
    { titolo: "Il monolocale", autore: "Lucio Battisti da 'Una giornata uggiosa' 1980" },
    { titolo: "Il muro del suono", autore: "Luciano Ligabue da 'Mondovisione' 2014" },
    { titolo: "Il nostro caro angelo", autore: "Lucio Battisti da 'Il nostro caro angelo' 1973" },
    { titolo: "Il nostro concerto", autore: "Umberto Bindi  1960" },
    { titolo: "Il pagliaccio", autore: "C. Cremonini" },
    { titolo: "Il Paradiso", autore: "Lucio Battisti da 'Il nostro caro angelo' 1973" },
    { titolo: "Il peso della valigia", autore: "Luciano Ligabue da 'Arrivederci mostro!' 2010" },
    { titolo: "Il ragazzo della via Gluck", autore: "Adriano Celentano da 'La festa' 1966" },
    { titolo: "Il sale della terra", autore: "Luciano Ligabue da 'Mondovisione' 2014" },
    { titolo: "Il tempo davanti", autore: "Luciano Ligabue da 'Start' 2019" },
    { titolo: "Il tempo di morire", autore: "Lucio Battisti da 'Emozioni' 1970" },
    { titolo: "Il vecchio e il bambino", autore: "Francesco Guccini da 'Radici' 1972" },
    { titolo: "Il veliero", autore: "Lucio Battisti da 'La batteria il contrabbasso eccetra' 1976" },
    { titolo: "Il vento", autore: "Lucio Battisti da 'Lucio Battisti' 1969" },
    { titolo: "Il volo", autore: "Zucchero Fornaciari" },
    { titolo: "Il volume delle tue bugie", autore: "Luciano Ligabue da 'Mondovisione' 2014" },
    { titolo: "Il vuoto", autore: "Franco Battiato da 'Il vuoto' 2007" },
    { titolo: "Imagine", autore: "John Lennon" },
    { titolo: "Impressioni di Settembre", autore: "PFM da 'Storia di un minuto' 1972" },
    { titolo: "In diretta nel vento", autore: "Pooh da 'Rotolando respirando' 1977" },
    { titolo: "In my place", autore: "Coldplay da 'A rush of blood to the head' 2002" },
    { titolo: "In prigione", autore: "Edoardo Bennato da 'Burattino senza fili' 1977" },
    { titolo: "Infiniti noi", autore: "Pooh 1973" },
    { titolo: "Innocenti evasioni", autore: "Lucio Battisti da 'Umanamente uomo il sogno' 1972" },
    { titolo: "Innu ri rusalini", autore: "Emanuele Calvo Brogato C." },
    { titolo: "Insieme a te sto bene", autore: "Lucio Battisti da 'Lucio Battisti Vol. 4' 1971" },
    { titolo: "Insieme è più bello", autore: "Gen Verde" },
    { titolo: "Insieme", autore: "Lucio Battisti per Mina 1970" },
    { titolo: "Io che amo solo te", autore: "Sergio Endrigo da 'Sergio Endrigo' 1961" },
    { titolo: "Io chi sono?", autore: "Franco Battiato da 'Il vuoto' 2007" },
    { titolo: "Io e te da soli", autore: "Lucio Battisti per Mina 1970" },
    { titolo: "Io gli ho detto no", autore: "Lucio Battisti da 'Il nostro caro angelo' 1973" },
    { titolo: "Io in questo mondo", autore: "Luciano Ligabue da 'Start' 2019" },
    { titolo: "Io per lei", autore: "Pino Daniele da 'Non calpestare i fiori nel deserto' 1995" },
    { titolo: "Io ritorno solo", autore: "Lucio Battisti per 'Formula tre' 1971" },
    { titolo: "Io ti venderei", autore: "Lucio Battisti da 'La batteria il contrabbasso eccetra' 1976" },
    { titolo: "Io vagabondo", autore: " Nomadi 1972" },
    { titolo: "Io vivro (senza te)", autore: "Lucio Battisti da 'Lucio Battisti' 1969" },
    { titolo: "Io vorrei non vorrei ma se vuoi", autore: "Lucio Battisti da 'Il mio canto libero' 1972" },

    { titolo: "Jast the way you are", autore: "Billy Joel" },
    { titolo: "Je so pazzo", autore: "Pino Daniele da 'Pino Daniele' 1979" },
    { titolo: "Je sto vicino a te", autore: "Pino Daniele da 'Pino Daniele' 1979" },

    { titolo: "KarmaPolice", autore: "Radiohead da 'OK Computer' 1997" },
    { titolo: "Kay e stata qui", autore: "Luciano Ligabue da 'Miss Mondo' 1999" },
    { titolo: "Keep on moving", autore: "Pino Daniele da 'Musicante' 1984" },

    { titolo: "L'amimale", autore: "Franco Battiato da 'Mondi lontanissimi' 1984" },
    { titolo: "L'amore conta", autore: "Luciano Ligabue da 'Nome e cognome' 2005" },
    { titolo: "L'amore è una cosa meravigliosa", autore: "S. Fain (M.) e P. F. Webster (T.) testo It. Devilli (psdnm. Alberto Semprini)" },
    { titolo: "L'anno che verrà", autore: "Lucio Dalla da 'Lucio Dalla' 1979" },
    { titolo: "L'aquila", autore: "Lucio Battisti da 'Il mio canto libero' 1972" },
    { titolo: "L'era del cinghiale bianco", autore: "Franco Battiato da 'L'era del cinghiale bianco' 1979" },
    { titolo: "L'impiccato", autore: "Francesco De Gregori da 'De Gregori' 1978" },
    { titolo: "L'interprete di un film", autore: "Lucio Battisti da 'Io tu noi tutti' 1977" },
    { titolo: "L'isola che non c'è", autore: "Edoardo Bennato da 'Sono solo canzonette' 1980" },
    { titolo: "L'odore del sesso", autore: "Luciano Ligabue da 'Miss Mondo' 1999" },
    { titolo: "L'ombra della Luce", autore: "Franco Battiato da 'Come un cammello in una grondaia' 1991" },
    { titolo: "L'ora dell'amore", autore: "Camaleonti   1968" },
    { titolo: "L'ultima luna", autore: "Lucio Dalla da 'Lucio Dalla' 1979" },
    { titolo: "L'unico Maestro", autore: "Matteo Civico" },
    { titolo: "La campana", autore: "Francesco De Gregori da 'De Gregori' 1978" },
    { titolo: "La canzone dei vecchi amanti", autore: "Franco Battiato da 'Fleurs' 1999" },
    { titolo: "La canzone del sole", autore: "Lucio Battisti da 'Lucio Battisti' 1969" },
    { titolo: "La canzone dell'amore perduto", autore: "Fabrizio de Andrè 'Tutto De Andrè' 1966" },
    { titolo: "La canzone della terra", autore: "Lucio Battisti da 'Il nostro caro angelo' 1973" },
    { titolo: "La canzone di Marinella", autore: "Fabrizio de Andrè 'Tutto De Andrè' 1966" },
    { titolo: "La casa in riva al mare", autore: "Lucio Dalla 1971" },
    { titolo: "La casa", autore: "Francesco De Gregori da 'Calypsos' 2006" },
    { titolo: "La cattiva compagnia", autore: "Luciano Ligabue da 'Start' 2019" },
    { titolo: "La collina dei ciliegi", autore: "Lucio Battisti da 'Il nostro caro angelo' 1973" },
    { titolo: "La compagnia", autore: "Lucio Battisti da 'La batteria il contrabbasso eccetra' 1976" },
    { titolo: "La cura", autore: "Franco Battiato da 'L'imboscata' 1996" },
    { titolo: "La donna cannone", autore: "Francesco De Gregori da 'Flirt' 1983" },
    { titolo: "La Fata", autore: "Edoardo Bennato da 'Burattino senza fili' 1977" },
    { titolo: "La guerra di Piero", autore: "Fabrizio de Andrè 'Tutto De Andrè' 1966" },
    { titolo: "La linea sottile", autore: "Luciano Ligabue da 'Arrivederci mostro!' 2010" },
    { titolo: "La luce dell'Est", autore: "Lucio Battisti da 'Il mio canto libero' 1972" },
    { titolo: "La mia canzone per Maria.htm", autore: "Lucio Battisti da 'Lucio Battisti' 1969" },
    { titolo: "La neve se ne frega", autore: "Luciano Ligabue da 'Mondovisione' 2014" },
    { titolo: "La sera dei miracoli", autore: "Lucio Dalla da 'Lucio Dalla' 1979" },
    { titolo: "La stagione dell'amore", autore: "Franco Battiato da 'Orizzonti perduti' 1983" },
    { titolo: "La storia", autore: "Francesco De Gregori da 'Scacchi e tarocchi' 1985" },
    { titolo: "La terra trema amore mio", autore: "Luciano Ligabue da 'Mondovisione' 2014" },
    { titolo: "La valigia dell'attore", autore: "Francesco De Gregori da 'La valigia dell'attore' 1997" },
    { titolo: "La vita è adesso", autore: "Claudio Baglioni da 'La vita è adesso' 1985" },
    { titolo: "Le allettanti promesse", autore: "Lucio Battisti da 'Il nostro caro angelo' 1973" },
    { titolo: "Le donne lo sanno", autore: "Luciano Ligabue da 'Nome e cognome' 2005" },
    { titolo: "Leggero", autore: "Luciano Ligabue da 'Buon compeanno Elvis' 1995" },
    { titolo: "Let It Be", autore: "The Beatles da 'Let it be' 1970" },
    { titolo: "Let the sunshine in", autore: "da 'Hair' 1969" },
    { titolo: "Letttera a G", autore: "Luciano Ligabue da 'Nome e cognome' 2005" },
    { titolo: "Libera uscita", autore: "Luciano Ligabue da 'Fuori come va?' 2002" },
    { titolo: "Liberi, liberi", autore: "Vasco Rossi da 'Liberi, liberi' 1989" },
    { titolo: "Linda", autore: "Pooh 1975" },
    { titolo: "Lode all'Inviolato", autore: "Franco Battiato da 'Caffè de la Paix' 1993" },
    { titolo: "Love Theme Morricone", autore: "Ennio Morricone da  'Nuovo cinema Paradiso' 1988" },
    { titolo: "Luci d'america", autore: "Luciano Ligabue da 'Start' 2019" },
    { titolo: "Luci-ha", autore: "Lucio Battisti da 'Il mio canto libero' 1972" },
    { titolo: "Lucky", autore: "Radiohead da 'Ok Computer' 1997" },
    { titolo: "Lucy in the sky", autore: "The Beatles da 'Sgt. Pepper's Lonely Hearts Club Band.' 1967" },
    { titolo: "Lui", autore: "Anonimo * Canto Scout '80-'90" },
    
    { titolo: "M'abituerò", autore: "Luciano Ligabue da 'Campovolo' 2011" },
    { titolo: "Ma è un canto brasileiro", autore: "Lucio Battisti da 'Il nostro caro angelo' 1973" },
    { titolo: "Ma il cielo è sempre + blu", autore: "Rino Gaetano 1975" },
    { titolo: "MadreTerra", autore: "Vincenzo Spampinato 2003" },
    { titolo: "Magic", autore: "Coldplay da 'Ghost stories' 2014" },
    { titolo: "Mai dire mai", autore: "Luciano Ligabue da 'Start' 2019" },
    { titolo: "Mais que nada", autore: "Sergio Mendes Jorge Ben Jor 1966" },
    { titolo: "Mal d'africa", autore: "Franco Battiato da 'Orizzonti perduti' 1983" },
    { titolo: "Maledetto gatto", autore: "Lucio Battisti da 'Una donna per amico' 1978" },
    { titolo: "Mameli Inno", autore: "Goffredo Mameli (T.) Michele Novaro (M.) 1847" },
    { titolo: "Mamma mia", autore: "Lucio Battisti per 'I camaleonti' 1969" },
    { titolo: "Mangiafuoco", autore: "Edoardo Bennato da 'Burattino senza fili' 1977" },
    { titolo: "Marcia Nuziale Wagner", autore: "Richard Wagner da 'Lohengrin' 1848" },
    { titolo: "Margherita", autore: "Riccardo Cocciante da 'Concerto per Margherita' 1976" },
    { titolo: "Mi ritorni in mente", autore: "Lucio Battisti da 'Emozioni' 1970" },
    { titolo: "Michelle", autore: "The Beatles da 'Rubber soul' 1965" },
    { titolo: "Miss Mondo 99", autore: "Luciano Ligabue da 'Miss Mondo' 1999" },
    { titolo: "Modena", autore: "Antonello Venditti da 'Buona domenica' 1979" },
    { titolo: "Mondo", autore: "Riccardo Fogli 1973" },
    { titolo: "Musica musica", autore: "Pino Daniele da 'Nero a metà' 1980" },
    { titolo: "My favorites things", autore: "Lyrics: Oscar Hammerstein, Music Richard Rodger 1959" },
    { titolo: "My sweet Lord", autore: "George Harrison da 'All things must pass' 1970" },
    { titolo: "My way", autore: "Frank Sinatra 1969 'Comme d'habitude' Claude François (T.) Jacques Revaux (M.) Trad. Paul Anka" },

    { titolo: "Napul'è", autore: "Pino Daniele da 'Terra mia' 1977" },
    { titolo: "Natale", autore: "Francesco De Gregori da 'De Gregori' 1978" },
    { titolo: "Neanche un minuto di non amore", autore: "Lucio Battisti da 'Io tu noi tutti' 1977" },
    { titolo: "Nel blu dipinto di blu", autore: "Franco Migliacci & Domenico Modugno - Sanremo 1958" },
    { titolo: "Nel cuore, nell'anima", autore: "Lucio Battisti da 'Lucio Battisti' 1969" },
    { titolo: "Nel sole, nel vento", autore: "Lucio Battisti da 'Lucio Battisti' 1969" },
    { titolo: "Nella fantasia - GabrielsOboe", autore: "Ennio Morricone da 'Mission' 1986" },
    { titolo: "Nessun dolore", autore: "Lucio Battisti da 'Una donna per amico' 1978" },
    { titolo: "Nessuno nessuno", autore: "Lucio Battisti per 'Formula tre' 1971" },
    { titolo: "Niente da capire", autore: "Francesco De Gregori da 'De Gregori' 1978" },
    { titolo: "Niente è come sembra", autore: "Franco Battiato da 'Il vuoto' 2007" },
    { titolo: "Niente paura", autore: "Luciano Ligabue da 'Primo tempo' 2008" },
    { titolo: "No dottore", autore: "Lucio Battisti da 'La batteria il contrabbasso eccetra' 1976" },
    { titolo: "No Surprises", autore: "Radiohead da 'Ok Computer' 1997" },
    { titolo: "Noi due nel mondo", autore: "Pooh 1972" },
    { titolo: "Non dovete badare al cantante", autore: "Luciano Ligabue da 'Buon compeanno Elvis' 1995" },
    { titolo: "Non è Francesca", autore: "Lucio Battisti da 'Lucio Battisti' 1969" },
    { titolo: "Non è tempo", autore: "Luciano Ligabue da 'Ligabue' 1990" },
    { titolo: "Notte che se ne va", autore: "Pino Daniele da 'Vai mò' 1981" },
    { titolo: "Notte prima degli esami", autore: "Antonello Venditti da 'Cuore' 1984" },
    { titolo: "Nun ce sta piacere", autore: "Pino Daniele da 'Vai mò' 1981" },
    { titolo: "Nun me scuccià", autore: "Pino Daniele da 'Nero a metà' 1980" },

    { titolo: "O' scarrafone", autore: "Pino Daniele da 'Un uomo in blues' 1991" },
    { titolo: "O' sole mio", autore: "(T.) G. Capurro, (M.) E. Di Capua 1898" },
    { titolo: "O' surdato 'nnammurato", autore: "(T.) Aniello Califano, (M.) Enrico Cannio 1915" },
    { titolo: "Oggi sono io", autore: "Alex Britti da 'Sanremo' 1999" },
    { titolo: "Oh happy day", autore: "Doddridge, Freylinghausen - Rimbault 1755" },
    { titolo: "One", autore: "U2 da 'Achtung baby' 1992" },
    { titolo: "Ora e allora", autore: "Luciano Ligabue da 'Campovolo' 2011" },
    { titolo: "Orgoglio e dignità", autore: "Lucio Battisti da 'Una giornata uggiosa' 1980" },
    { titolo: "Over the rainbow", autore: "Harold Arlen (M.), E. Y. Harburg (T.) 1939" },

    { titolo: "Paolo pa", autore: "Banco da 'Urgentissimo' 1980" },
    { titolo: "Paradise", autore: "Coldplay da 'Mylo Xyloto' 2011" },
    { titolo: "ParanoidAndroid", autore: "Radiohead da 'Ok Computer' 1997" },
    { titolo: "Parole di burro", autore: "Carmen Consoli da 'Stato di necessità' 2000" },
    { titolo: "Parsifal", autore: "Pooh da 'Parsifal' 1973" },
    { titolo: "Passacaglia", autore: "Franco Battiato da 'Apriti sesamo' 2012" },
    { titolo: "Peace on earth", autore: "U2 da 'All That You Can't Leave Behind' 2000" },
    { titolo: "Pensieri e parole", autore: "Lucio Battisti - Mogol (Lucio Rapetti) 1971" },
    { titolo: "Per Elisa", autore: "Franco Battiato, per Alice, Giusto Pio da 31° Sanremo 1981" },
    { titolo: "Per sempre", autore: "Luciano Ligabue da 'Mondovisione' 2014" },
    { titolo: "Per una lira", autore: "Lucio Battisti / Renato Angiolini- Mogol (Lucio Rapetti) 1966" },
    { titolo: "Perche no", autore: "Lucio Battisti da 'Una donna per amico' 1978" },
    { titolo: "Perche non sei una mela", autore: "Lucio Battisti da 'Una giornata uggiosa' 1980" },
    { titolo: "Perfect day", autore: "Lou Reed 1972" },
    { titolo: "Pianeti", autore: "Ultimo da 'Pianeti' 2017" },
    { titolo: "Piazza Grande", autore: "Lucio Dalla e Ron (M.) Gianfranco Baldazzi e Sergio Bardotti (T.) 1972" },
    { titolo: "Piccola stella senza cielo", autore: "Luciano Ligabue da 'Ligabue' 1990" },
    { titolo: "Poesia senza veli", autore: "Ultimo da 'Peter Pan' 2017" },
    { titolo: "Polvere di stelle", autore: "Luciano Ligabue da 'Start' 2019" },
    { titolo: "Povera patria", autore: "Franco Battiato da 'Come un cammello in una grondaia' 1991" },
    { titolo: "Prendila così", autore: "Lucio Battisti da 'Una donna per amico' 1978" },
    { titolo: "Pride", autore: "U2 da 'The Unforgettable Fire' 1984" },
    { titolo: "Primavera", autore: "Riccardo Cocciante da 'Concerto per Margherita' 1976" },
    { titolo: "Prospettiva Nevskij", autore: "Franco Battiato da 'Patriots' 1980" },
    { titolo: "Puozze passa nu guaio", autore: "Pino Daniele da 'Nero a metà' 1980" },
    { titolo: "Putesse essere allero", autore: "Pino Daniele da 'Pino Daniele' 1979" },

    { titolo: "Quand'ero giovane", autore: "Franco Battiato da 'Apriti sesamo' 2012" },
    { titolo: "Quando canterai la tua canzone", autore: "Luciano Ligabue da 'Arrivederci mostro!' 2010" },
    { titolo: "Quando finisce un amore", autore: "Ricardo Cocciante da 'Anima' 1974" },
    { titolo: "Quando sarai grande", autore: "Edoardo Bennato da 'Burattino senza fili' 1977" },
    { titolo: "Quanno chiove", autore: "Pino Daniele da 'Nero a metà' 1980" },
    { titolo: "Quant'è bedda la mà zzita", autore: "Popolare siciliano" },
    { titolo: "Quattro cani", autore: "Francesco De Gregori da 'Rimmel' 1975" },
    { titolo: "Quello che mi fa la guerra", autore: "Luciano Ligabue da 'Start' 2019" },
    { titolo: "Questa e la mia vita", autore: "Luciano Ligabue da 'Fuori come va?' 2002" },
    { titolo: "Questione di cellule", autore: "Lucio Battisti da 'Io tu noi tutti' 1977" },
    { titolo: "Questo amore", autore: "Lucio Battisti da 'Una giornata uggiosa' 1980" },
    { titolo: "Questo folle sentimento", autore: "Lucio Battisti per 'Formula tre' 1969" },
    { titolo: "Questo piccolo grande amore", autore: "Claudio Baglioni da 'Questo piccolo grande amore' 1972" },
    
    { titolo: "Radio Varsavia", autore: "Franco Battiato da 'L'arca di Noè' 1982" },
    { titolo: "Raggio di sole", autore: "Francesco De Gregori da 'De Gregori' 1978" },
    { titolo: "Regalami il tuo sogno", autore: "Luciano Ligabue da 'Lambrusco rose & popcorn' 1991" },
    { titolo: "Reginella", autore: "(T.) Libero Bovio, (M.) Gaetano Lama 1917" },
    { titolo: "Reign of Love", autore: "Coldplay da 'Viva la vida' 2008" },
    { titolo: "Renoir", autore: "Francesco De Gregori da 'De Gregori' 1978" },
    { titolo: "Respirando", autore: "Lucio Battisti da 'La batteria il contrabbasso eccetra' 1976" },
    { titolo: "Resta qui con noi", autore: "Gen Rosso" },
    { titolo: "Ricordati di me", autore: "Antonello Venditti da 'In questo mondo di ladri' 1988" },
    { titolo: "Rimmel", autore: "Francesco De Gregori da 'Rimmel' 1975" },
    { titolo: "Roma capoccia", autore: "Antonello Venditti da 'Theorius campus' 1972" },
    { titolo: "Roma nun fa la stupida stasera", autore: "Garinei/Giovannini/Trovajoli da 'Rugantino' 1962" },

    { titolo: "Sabato pomeriggio", autore: "Claudio Baglioni da 'Sabato pomeriggio' 1975" },
    { titolo: "Santa Lucia", autore: "(M.) Teodoro Cottrau (T.) Enrico Cossovich 1849" },
    { titolo: "Sara", autore: "Antonello Venditti da 'Sotto il segno dei pesci' 1978" },
    { titolo: "Se - Love theme Morricone", autore: "Ennio Morricone da  'Nuovo cinema Paradiso' 1988" },
    { titolo: "Se bruciasse la città", autore: "Massimo Ranieri (T.) G. Bigazzi, (M.) E. Polito, T. Savio 1969" },
    { titolo: "Se io fossi un angelo", autore: "Lucio Dalla da 'Bugie' 1986" },
    { titolo: "Se io lavoro", autore: "Le orme da 'Storia o leggenda' 1977" },
    { titolo: "Se telefonando", autore: "E. Morricone, M. Costanzo, G. De Chiara per Mina 1966" },
    { titolo: "Secondo imbrunire", autore: "Franco Battiato da 'Fisiognomica' 1988" },
    { titolo: "Seduto in riva al fosso", autore: "Luciano Ligabue da 'Buon compeanno Elvis' 1995" },
    { titolo: "Sempre e per sempre", autore: "Francesco De Gregori da 'Amore nel pomeriggio' 2001" },
    { titolo: "Sentimento nuevo", autore: "Franco Battiato da 'La voce del padrone' 1981" },
    { titolo: "Sette e quaranta", autore: "Lucio Battisti da 'Emozioni' 1970" },
    { titolo: "Shine on you crazy diamond", autore: "Pink Floyd da 'Wish you where here' 1975" },
    { titolo: "Shiver", autore: "Coldplay da 'Parachutes' 2000" },
    { titolo: "Si può dare di più", autore: "Morandi-Ruggeri, Tozzi SanRemo 1987" },
    { titolo: "Sì viaggiare", autore: "Lucio Battisti da 'Io tu noi tutti' 1977" },
    { titolo: "Si viene e si va", autore: "Luciano Ligabue da 'Miss Mondo' 1999" },
    { titolo: "Siamo chi siamo", autore: "Luciano Ligabue da 'Mondovisione' 2014" },
    { titolo: "Sicilia bedda", autore: "Gaetano Emanuel-Calì (Canterini etnei) 1929" },
    { titolo: "Sicily", autore: "Pino Daniele da 'Che Dio ti benedica' 1993" },
    { titolo: "Smoke gets in your eyes", autore: "Platters 1958" },
    { titolo: "Sogni di Rock'n Roll", autore: "Luciano Ligabue da 'Ligabue' 1990" },
    { titolo: "Soli", autore: "Lucio Battisti da 'Io tu noi tutti' 1977" },
    { titolo: "Something", autore: "The Beatles da 'Abbey Road' 1969" },
    { titolo: "Sometimes you cant make it on your own", autore: "U2 da 'How to dismantel an atom bomb' 2004" },
    { titolo: "Sono più sereno", autore: "Le Vibrazioni da 'Le vibrazioni' 2003" },
    { titolo: "Sono qui per l'amore", autore: "Luciano Ligabue da 'Nome e cognome' 2005" },
    { titolo: "Sono sempre i sogni a dare forma al mondo", autore: "Luciano Ligabue da 'Mondovisione' 2014" },
    { titolo: "Sotto il segno dei pesci", autore: "Antonello Venditti da 'Sotto il segno dei pesci' 1978" },
    { titolo: "Space Oddity", autore: "David Bowie da 'Space oddity' 1969" },
    { titolo: "Spies", autore: "Coldplay da 'Parachutes' 2000" },
    { titolo: "Stairway to heaven", autore: "Led Zeppelin da 'Led Zeppelin IV' 1971" },
    { titolo: "Stella di mare", autore: "Lucio Dalla da 'Lucio Dalla' 1979" },
    { titolo: "Stop crying your heart out", autore: "Oasis 'Heathen Chemistry' 2002" },
    { titolo: "Strada facendo", autore: "Claudio Baglioni da 'Strada facendo' 1981" },
    { titolo: "Stranizza d'amuri", autore: "Franco Battiato da 'L'era del cinghiale bianco' 1979" },
    { titolo: "Strawberry fields", autore: "Beatles da 'Strawberry Fields Forever' 1967" },
    { titolo: "Sulla mia strada", autore: "Luciano Ligabue da 'Miss Mondo' 1999" },
    { titolo: "Summer on a solitary beach", autore: "Franco Battiato da 'A voce del padrone' 1981" },
    { titolo: "Sunday bloody sunday", autore: "U2 da 'War' 1983" },
    { titolo: "Suonare suonare", autore: "PFM da 'Suonare Suonare' 1980" },
    { titolo: "Symbolum '77 (Tu Sei la mia vita)", autore: "Pierangelo Sequeri" },
    
    { titolo: "Tanta voglia di lei", autore: "Pooh 1971" },
    { titolo: "Talè cchi ddannu", autore: "Anonimo Popolare Goliardico" },
    { titolo: "Tanto pe' canta'", autore: "Nino Manfredi - Ettore Petrolini, Natale Alberto Simeoni 1932" },
    { titolo: "Te lo leggo negli occhi", autore: "Franco Battiato (S. Endrigo) da 'Fleurs' 1999" },
    { titolo: "The Great Gig in the sky", autore: "Pink Floyd da 'The dark side of the moon' 1973" },
    { titolo: "The Logical song", autore: "Supertramp da 'Breakfast in America' 1979" },
    { titolo: "The prayer", autore: "C.Dion da 'These Are Special Times' 1999" },
    { titolo: "The Scientist", autore: "Coldplay da 'A Rush of blood to the head' 2002" },
    { titolo: "Ti sento", autore: "Luciano Ligabue da 'Fuori come va?' 2002" },
    { titolo: "Ticket to ride", autore: "The Beatles da 'Help' 1965" },
    { titolo: "Time", autore: "Pink Floyd da 'The dark side of the moon' 1973" },
    { titolo: "Torna a Surriento", autore: "(M.) Ernesto De Curtis (T.) Giambattista 1894" },
    { titolo: "Tu ca nun chiagne", autore: "(T.) Libero Bovio, (M.) Ermesto De Curtis 1915" },
    { titolo: "Tu che conosci il cielo", autore: "Luciano Ligabue da 'Fuori come va?' 2002" },
    { titolo: "Tu come stai", autore: "Claudio Baglioni da 'E tu come stai?' 1978" },
    { titolo: "Tu dimmi quando", autore: "Pino Daniele da 'Sotto 'o sole' 1991" },
    { titolo: "Tu grillo parlante", autore: "Edoardo Bennato da 'Burattino senza fili' 1977" },
    { titolo: "Tu Sei la mia vita (Symbolum '77)", autore: "" },
    { titolo: "Tu sei lei", autore: "Luciano Ligabue da 'Mondovisione' 2014" },
    { titolo: "Tu vuò fà l'americano", autore: "Renato Carosone (M.), Nicola Salerno 'Nisa'(T.) 1956" },
    { titolo: "Tutta n'ata storia", autore: "Pino Daniele da 'Bella 'mbriana' 1982" },
    { titolo: "Tutto quello che un uomo", autore: "Sergio Cammariere da 'Dalla pace del mare lontano' 2003" },
    
    { titolo: "U cuntu", autore: "Franco Battiato da 'Inners auge' 2010" },
    { titolo: "Umanamente uomo il sogno", autore: "Lucio Battisti da 'Umanamente uomo il sogno' 1972" },
    { titolo: "Un colpo all'anima", autore: "Luciano Ligabue da 'Arrivederci mostro!' 2010" },
    { titolo: "Un giorno che non va", autore: "Pino Daniele da 'Vai mo' 1981" },
    { titolo: "Un giorno credi", autore: "Edoardo Bennato da 'Non farti cadere le braccia' 1973" },
    { titolo: "Un Giudice", autore: "Fabrizio de Andre' da 'Non al denaro, non all'amore ne' al cielo' 1971" },
    { titolo: "Un senso", autore: "Vasco Rossi da 'Buoni o cattivi' 2004" },
    { titolo: "Un uomo che ti ama", autore: "Lucio Battisti da 'La batteria il contrabbasso eccetra' 1976" },
    { titolo: "Un'altra vita", autore: "Franco Battiato da 'Orizzonti perduti' 1983" },
    { titolo: "Un'avventura", autore: "Lucio Battisti da 'Lucio Battisti' 1969" },
    { titolo: "Una canzone per te", autore: "Vasco Rossi da 'Bollicine' 1983" },
    { titolo: "Una donna per amico", autore: "Lucio Battisti da 'Una donna per amico' 1978" },
    { titolo: "Una giornata uggiosa", autore: "Lucio Battisti da 'Una donna per amico' 1978" },
    { titolo: "Una settimana un giorno", autore: "Edoardo Bennato da 'Non farti cadere le braccia' 1973" },
    { titolo: "Una storia sbagliata", autore: "Fabrizio De Adrè 1980" },
    { titolo: "Una vita da mediano", autore: "Luciano Ligabue da 'Miss Mondo' 1999" },
    { titolo: "Una vita viva", autore: "Lucio Battisti da 'Una donna per amico' 1978" },
    { titolo: "Una", autore: "Lucio Battisti da 'Amore non amore' 1971" },
    { titolo: "Uno in più", autore: "Lucio Battisti da 'Lucio Battisti' 1969" },
    { titolo: "Uomini soli", autore: "Pooh da 'Uomini soli' 1990" },
    { titolo: "Up patriots to arm", autore: "Franco Battiato da 'Patriots' 1980" },
    { titolo: "Us and them", autore: "Pink Floyd da 'The dark side of the moon' 1973" },
    
    { titolo: "Vendo casa", autore: "Lucio Battisti per i 'Dik Dik' 1971" },
    { titolo: "Veni l'Autunnu", autore: "Franco Battiato da 'Fisiognomica' 1988" },
    { titolo: "Vento nel vento", autore: "Lucio Battisti da 'Il mio canto libero' 1972" },
    { titolo: "Via del campo", autore: "Fabrizio de Andrè 'Tutto De Andrè' 1966" },
    { titolo: "Vieni da me", autore: "Le Vibrazioni da 'Le vibrazioni' 2003" },
    { titolo: "Vieni via con me", autore: "Paolo Conte da 'Paris milonga' 1981" },
    { titolo: "Vita spericolata", autore: "Vasco Rossi da 'Bollicine' 1983" },
    { titolo: "Viva l'Italia", autore: "Francesco De Gregori da 'Viva l'Italia' 1979" },
    { titolo: "Viva la vida", autore: "Coldplay da 'Viva la vida' 2008" },
    { titolo: "Viva", autore: "Luciano Ligabue da 'Buon compeanno Elvis' 1995" },
    { titolo: "Vivere a orecchio", autore: "Luciano Ligabue da 'Nome e cognome' 2005" },
    { titolo: "Voce 'e notte", autore: "(T.) Eduardo Nicolardi (M.) Ernesto De Curtis 1904" },
    { titolo: "Voglio di più", autore: "Pino Daniele da 'Nero a meta' 1980" },
    { titolo: "Voglio vederti danzare", autore: "Franco Battiato da 'L'arca di Noe' 1982" },
    { titolo: "Voglio volere", autore: "Luciano Ligabue da 'Fuori come va?' 2002" },

    { titolo: "Warning Sign", autore: "Coldplay da 'A Rush of blood to the head' 2002" },
    { titolo: "We shall overcome", autore: "Peter Seeger/Joan Baets, Reverend Charles Tindley of Philadelphia 1903" },
    { titolo: "What if", autore: "Coldplay da 'X & Y' 2005" },
    { titolo: "What's up", autore: "4 non blondes Linda Perry" },
    { titolo: "When I'm sixty four", autore: "The Beatles da 'Lonely hearts club band' 1967" },
    { titolo: "Where the streets have no name", autore: "U2 da 'The Joshua tree' 1987" },
    { titolo: "While my guitar gently weeps", autore: "George Harrison - The Beatles da 'White Album' 1968" },
    { titolo: "White Christmas", autore: "B.Chrosby Irving Berlin 1940" },
    { titolo: "Wish you where here", autore: "Pink Floyd da 'Wish you where here' 1975" },
    { titolo: "With a little help from my friends", autore: "The Beatles da 'Sgt. Pepper's Lonely Hearts Club Band.' 1967" },
    { titolo: "With or without you", autore: "U2 da 'The Joshua tree' 1987" },
    { titolo: "Wonderful tonight", autore: "Eric Clapton da 'SlowHand' 1977" },

    { titolo: "Yellow", autore: "Coldplay da 'Parachutes' 2000" },
    { titolo: "Yes I know my way", autore: "Pino Daniele da 'Vai mo' 1981" },
    { titolo: "Yesterday", autore: "The Beatles da 'Help!' 1965" }
    
];